---
driver_plugin: docker
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.10
  driver_config:
    image: ubuntu:12.10
    platform: ubuntu
  run_list:
  - recipe[apt]

- name: debian-6.0.7
  driver_config:
    image: tianon/debian:6.0.7
    platform: debian
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[apticron]
  attributes:

